exclude: 'docs|node_modules|build|dist|migrations|.git|.tox'
default_stages: [commit]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: mixed-line-ending
        args:
          - --fix=auto
        language_version: python3.10
      - id: requirements-txt-fixer
        language_version: python3.10
      - id: trailing-whitespace
        language_version: python3.10
      - id: end-of-file-fixer
        language_version: python3.10
      - id: check-added-large-files
        args: ["--maxkb=150000"]
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: fix-encoding-pragma
        args: ["--remove"]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        additional_dependencies: [toml]
        language_version: python3.10
      - id: isort
        name: isort (cython)
        types: [ cython ]
      - id: isort
        name: isort (pyi)
        types: [ pyi ]

  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
        language_version: python3.10

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        language_version: python3.10
        args: ['--config=.flake8']
        additional_dependencies: [flake8-isort]
