version: '3.0'
services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "som-celery-worker"
    env_file:
      - $ENV_FILE
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: make api
    container_name: "som-api"
    env_file:
      - $ENV_FILE
    ports:
      - "127.0.0.1:8000:${PORT-8000}"  # take env var PORT, use 8000 as default
