version: '3.0'
services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "som-celery-worker"
    volumes:
      - "./:/project"
    env_file:
      - $ENV_FILE
    environment:
      - CELERY_BROKER
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: make api
    container_name: "som-api"
    volumes:
      - "./:/project"
    env_file:
      - $ENV_FILE
    ports:
      - "127.0.0.1:8000:${APP_PORT-8000}"  # take env var APP_PORT, use 8000 as default
    environment:
      - CELERY_BROKER
