version: '2.0'
services:
  worker:
    image: python:3.9-alpine
    command: ash -c "apk add --no-cache build-base libcurl curl-dev; pip3 install -r requirements.txt; celery -A tasks worker --loglevel=info"
    volumes:
      - "./som:/som"
    working_dir: /som
    restart: on-failure
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - SQS_URL
